name: "Godot Export"
on: [push, workflow_dispatch]
env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: Chronos-Descent
  PROJECT_PATH: "."
jobs:
  export-platforms:
    name: Export for ${{ matrix.platform.name }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.3
    strategy:
      matrix:
        platform:
          - name: windows
            preset: "Windows Desktop"
            ext: "exe"
          - name: linux
            preset: "Linux"
            ext: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          [ -d /root/.config/godot ] && mv /root/.config/godot ~/.config/godot || true
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Build for ${{ matrix.platform.name }}
        shell: bash
        run: |
          mkdir -v -p build/${{ matrix.platform.name }}
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          EXPORT_FLAG="${{ matrix.platform.debug == true && '--export-debug' || '--export-release' }}"
          EXPORT_OUTPUT="$EXPORT_DIR/$EXPORT_NAME.${{ matrix.platform.ext }}"
          godot --headless --verbose $EXPORT_FLAG "${{ matrix.platform.preset }}" $EXPORT_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}${{ matrix.platform.debug == true && '_debug' || '_release' }}
          path: build/
