name: "Godot Export"
on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      platform:
        description: "Build platform (all, Android, Windows, Linux)"
        type: choice
        options:
          - all
          - Android
          - Windows
          - Linux
        default: all
        required: true
      debug:
        description: "Build debug version"
        type: boolean
        default: true
        required: false

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    outputs:
      build_platforms: ${{ steps.set-platforms.outputs.platforms }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Builder
          push: false
          load: true
          tags: chronos-descent-builder:latest
          
      - name: Set platforms to build
        id: set-platforms
        run: |
          if [ "${{ github.event.inputs.platform }}" == "all" ] || [ "${{ github.event.inputs.platform }}" == "" ]; then
            echo "platforms=[\"Android\", \"Windows\", \"Linux\"]" >> $GITHUB_OUTPUT
          else
            echo "platforms=[\"${{ github.event.inputs.platform }}\"]" >> $GITHUB_OUTPUT
          fi

  export-platform:
    name: Export for ${{ matrix.platform }}
    needs: build-docker-image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: ${{ fromJson(needs.build-docker-image.outputs.build_platforms) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Builder
          push: false
          load: true
          tags: chronos-descent-builder:latest
      
      - name: Run ${{ matrix.platform }} build
        id: build
        run: |
          # Determine if we're doing a debug or release build
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            IS_DEBUG="${{ github.event.inputs.debug == 'true' }}"
          else
            IS_DEBUG="true"
          fi
          
          # Create build directory
          mkdir -p build
          
          # Run the Docker container with the appropriate command
          if [ "$IS_DEBUG" == "true" ]; then
            docker run --rm -v ${{ github.workspace }}:/project -v ${{ github.workspace }}/build:/project/build chronos-descent-builder ${{ matrix.platform }}
          else
            docker run --rm -v ${{ github.workspace }}:/project -v ${{ github.workspace }}/build:/project/build chronos-descent-builder ${{ matrix.platform }} release
          fi
          
          # Save build type for artifact upload
          if [ "$IS_DEBUG" == "true" ]; then
            echo "BUILD_TYPE=debug" >> $GITHUB_ENV
          else
            echo "BUILD_TYPE=release" >> $GITHUB_ENV
          fi
          
          # Verify build output
          ls -la build/
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chronos-Descent_${{ matrix.platform }}_${{ env.BUILD_TYPE }}
          path: build/